pages:
  stage: deploy
  script:
  - apt-get install -y nodejs
  - npm install
  - mkdir .public
  - cp -r * .public
  - mv .public public
  - node index.js
  artifacts:
    paths:
    - public
  only:
  - master
  
